apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-caffe-extract
  namespace: default
spec:
  # Add fields here
  model: "harbor.caicloud.com/release/caffe:v1"
  extraction:
    format: "CaffeModel"

