apiVersion: kleveross.io/v1alpha1
kind: ModelJob
metadata:
  name: modeljob-caffe-convert
  namespace: default
spec:
  # Add fields here
  model: "harbor.caicloud.com/release/caffe:v1"
  desiredTag: "harbor.caicloud.com/release/caffe2_convert:v2"
  conversion:
    mmdnn:
      from: "CaffeModel"
      to: "NetDef"

