---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: percent-diversion
  namespace: kleveross-system
spec:
  name: savedmodel
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        metadata:
          name: savedmodel
        containers:
        - name: savedmodel
          image: lever-dev.cargo.io/release/trtserver:0.1.0
          imagePullPolicy: Always
          ports:
          - name: http
            protocol: TCP
            containerPort: 8000
          env:
          - name: MODEL_STORE
            value: /mnt
          - name: SERVING_NAME
            value: models
          volumeMounts:
          - name: models-mnt
            mountPath: /mnt/models
          readinessProbe:
            failureThreshold: 30
            timeoutSeconds: 5
            httpGet:
              path: /api/status/models
              scheme: HTTP
              port: 8000
          livenessProbe:
            failureThreshold: 30
            timeoutSeconds: 5
            httpGet:
              path: /api/status/models
              scheme: HTTP
              port: 8000
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
        initContainers:
        - name: model-initializer
          args: ["harbor-harbor-core.kleveross-system/release/savedmodel:v1", "/mnt/models"]
          image: ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.6
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY_ID
            value: admin
          - name: AWS_SECRET_ACCESS_KEY
            value: ORMBtest12345
          - name: ROOTPATH
            value: /mnt
          volumeMounts:
          - name: models-mnt
            mountPath: /mnt/models
        securityContext:
          privileged: true
          runAsUser: 0
          fsGroup: 10000
        volumes:
        - name: models-mnt
          emptyDir: {}
    graph:
      name: savedmodel
      children: []
      modelUri: harbor-harbor-core.kleveross-system/release/savedmodel:v1
      serviceAccountName: default
      endpoint:
        service_port: 8000
        type: REST
    name: savedmodel
    traffic: 20
    replicas: 1
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        metadata:
          name: pmml
        containers:
        - name: pmml
          image: lever-dev.cargo.io/release/openscoring:0.1.0
          imagePullPolicy: Always
          ports:
          - name: http
            protocol: TCP
            containerPort: 8000
          env:
          - name: MODEL_STORE
            value: /mnt/models
          - name: SERVING_NAME
            value: models
          volumeMounts:
          - name: models-mnt
            mountPath: /mnt/models
          readinessProbe:
            failureThreshold: 30
            timeoutSeconds: 5
            httpGet:
              path: /openscoring/model/models
              scheme: HTTP
              port: 8000
          livenessProbe:
            failureThreshold: 30
            timeoutSeconds: 5
            httpGet:
              path: /openscoring/model/models
              scheme: HTTP
              port: 8000
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
        initContainers:
        - name: model-initializer
          args: ["harbor-harbor-core.kleveross-system/release/pmml:v1", "/mnt/models"]
          image: ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.6
          imagePullPolicy: Always
          env:
          - name: AWS_ACCESS_KEY_ID
            value: ormbtest
          - name: AWS_SECRET_ACCESS_KEY
            value: ORMBtest12345
          - name: ROOTPATH
            value: /mnt
          volumeMounts:
          - name: models-mnt
            mountPath: /mnt/models
        securityContext:
          privileged: true
          runAsUser: 0
          fsGroup: 10000
        volumes:
        - name: models-mnt
          emptyDir: {}
    graph:
      name: pmml
      children: []
      modelUri: harbor-harbor-core.kleveross-system/release/pmml:v1
      serviceAccountName: default
      endpoint:
        service_port: 8000
        type: REST
    name: pmml
    traffic: 80
    replicas: 1