# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  model-registry-unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
           go-version: 1.14.7
        id: go
      - uses: actions/checkout@v2
        with:
         path: src/github.com/kleveross/klever-model-registry
      - name: setup env
        run: |
          cd src/github.com/kleveross/klever-model-registry
          pwd
          go env
          echo "::set-env name=GOPATH::$(go env GOPATH):$GITHUB_WORKSPACE"
          echo "::add-path::$(go env GOPATH)/bin"
      - name: before_install
        run: |
          # get coveralls.io support
          go get github.com/mattn/goveralls
          # install kubebuilder
          wget https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz
          tar -zxvf kubebuilder_2.3.1_linux_amd64.tar.gz
          mv kubebuilder_2.3.1_linux_amd64 kubebuilder
          sudo mv kubebuilder /usr/local
      - name: script
        run: |
          cd src/github.com/kleveross/klever-model-registry
          go test -mod=vendor ./pkg/... -race -covermode atomic -coverprofile profile.cov
      - name: send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: src/github.com/kleveross/klever-model-registry/profile.cov
          flag-name: unit-test
          parallel: true

  model-registry-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
           go-version: 1.14.7
        id: go
      - uses: actions/checkout@v2
        with:
         path: src/github.com/kleveross/klever-model-registry
      - name: setup env
        run: |
          cd src/github.com/kleveross/klever-model-registry
          pwd
          go env
          echo "::set-env name=GOPATH::$(go env GOPATH):$GITHUB_WORKSPACE"
          echo "::add-path::$(go env GOPATH)/bin"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install
        run: |
          cd src/github.com/kleveross/klever-model-registry
          make build

  model-registry-build-macOS:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
            go-version: 1.14.7
        id: go
      - uses: actions/checkout@v2
        with:
          path: src/github.com/kleveross/klever-model-registry
      - name: setup env
        run: |
          cd src/github.com/kleveross/klever-model-registry
          pwd
          go env
          echo "::set-env name=GOPATH::$(go env GOPATH):$GITHUB_WORKSPACE"
          echo "::add-path::$(go env GOPATH)/bin"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: install
        run: |
          cd src/github.com/kleveross/klever-model-registry
          make build
